spring:
  config:
    activate:
      on-profile: dev
    import:
      - submodule/application-db-dev.yaml

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  #  properties:
#    hibernate:
#      format_sql: true
