spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:./data/demo;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql.init.mode: always
